### ISSUE TITLE
About the experimental details

### ISSUE THREAD

**Issue by hwseo95** [seunghan96/pits#4]
Reproducing your paper, I have a question on experiments for self-supervised PITS.

For self-supervised PITS, did you use the equal input sequence length for time series forecasting experiment in Table 2?
The provided parameter in your github says the input sequence length is different for each dataset.
Which input length did you use for PITS implementation and other baselines?

Did you use non-overlapping patches or overlapping patches? In the appendix, the numbers of patches are different for each dataset even if it uses the same patch length. Thus, I guess you use different stride and overlapping patches?

Can you tell me more detailed (input length, patch length, stride) for all experimental datasets of self-supervised PITS?

**Comment by seunghan96** [comment]
I used the TS input length as follows:
- SSL: non-overlapping
- SL: overlapping (with stride as half of the patch size)
This is in accordance with our baseline, PatchTST.

Please refer to Section C.1.Time Series Forecasting, in the appendix.

Thank you :)
